export const ServiceActionTypes = {
    SERVICES_PROG: 'SERVICES_PROG',
    SERVICES_SUCC: 'SERVICES_SUCC',
    SERVICES_FAIL: 'SERVICES_FAIL',

    GET_SERVICE_FAQ_PROG: 'GET_SERVICE_FAQ_PROG',
    GET_SERVICE_FAQ_SUCC: 'GET_SERVICE_FAQ_SUCC',
    GET_SERVICE_FAQ_FAIL: 'GET_SERVICE_FAQ_FAIL',

    GET_SERVICE_PROG: 'GET_SERVICE_PROG',
    GET_SERVICE_SUCC: 'GET_SERVICE_SUCC',
    GET_SERVICE_FAIL: 'GET_SERVICE_FAIL',

    CLEAR_SERVICE: 'CLEAR_SERVICE',
    CLEAR_SERVICES: 'CLEAR_SERVICES',

};