export const ServiceActionTypes = {
    SERVICES_PROG: 'SERVICES_PROG',
    SERVICES_SUCC: 'SERVICES_SUCC',
    SERVICES_FAIL: 'SERVICES_FAIL',

    GET_SERVICE_FAQ_PROG: 'GET_SERVICE_FAQ_PROG',
    GET_SERVICE_FAQ_SUCC: 'GET_SERVICE_FAQ_SUCC',
    GET_SERVICE_FAQ_FAIL: 'GET_SERVICE_FAQ_FAIL',

    CLEAR_SERVICE_FAQ: 'CLEAR_SERVICE_FAQ'

};