export const NotificationActionTypes = {

    SHOW_SUCCESS_NOTIFICATION: 'SHOW_SUCCESS_NOTIFICATION',
    HIDE_SUCCESS_NOTIFICATION: 'HIDE_SUCCESS_NOTIFICATION',

    SHOW_ERROR_NOTIFICATION: 'SHOW_ERROR_NOTIFICATION',
    HIDE_ERROR_NOTIFICATION: 'HIDE_ERROR_NOTIFICATION'

};