export const LovActionTypes = {
    GET_LOV_PROG: 'GET_LOV_PROG',
    GET_LOV_SUCC: 'GET_LOV_SUCC',
    GET_LOV_FAIL: 'GET_LOV_FAIL',


    GET_PRIVACY_POLICY_PROG: 'GET_PRIVACY_POLICY_PROG',
    GET_PRIVACY_POLICY_SUCC: 'GET_PRIVACY_POLICY_SUCC',
    GET_PRIVACY_POLICY_FAIL: 'GET_PRIVACY_POLICY_FAIL',


};