export const MyBasketActionTypes = {

    ADD_TO_BASKET: 'ADD_TO_BASKET',

    INCREMENT_QTY: 'INCREMENT_QTY',

    DECREMENT_QTY: 'DECREMENT_QTY',

    REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET',

    SET_BASKET: 'SET_BASKET',

    CLEAR_BASKET: 'CLEAR_BASKET',

    VALIDATE_PROMO_COUPON_PROG: 'VALIDATE_PROMO_COUPON_PROG',
    VALIDATE_PROMO_COUPON_SUCC: 'VALIDATE_PROMO_COUPON_SUCC',
    VALIDATE_PROMO_COUPON_FAIL: 'VALIDATE_PROMO_COUPON_FAIL',

    VALIDATE_REFERRAL_COUPON_PROG: 'VALIDATE_REFERRAL_COUPON_PROG',
    VALIDATE_REFERRAL_COUPON_SUCC: 'VALIDATE_REFERRAL_COUPON_SUCC',
    VALIDATE_REFERRAL_COUPON_FAIL: 'VALIDATE_REFERRAL_COUPON_FAIL',

    USE_REFERRAL: 'USE_REFERRAL',

    CLEAR_PROMO_COUPON: 'CLEAR_PROMO_COUPON',

    CLEAR_COUPON: 'CLEAR_COUPON',

    SET_COUPON: 'SET_COUPON'

};