export const AddressActionTypes = {
    GET_ADDRESSES_PROG: 'GET_ADDRESSES_PROG',
    GET_ADDRESSES_SUCC: 'GET_ADDRESSES_SUCC',
    GET_ADDRESSES_FAIL: 'GET_ADDRESSES_FAIL',

    SAVE_ADDRESS_PROG:'SAVE_ADDRESS_PROG',
    SAVE_ADDRESS_SUCC:'SAVE_ADDRESS_SUCC',
    SAVE_ADDRESS_FAIL:'SAVE_ADDRESS_FAIL',

    UPDATE_ADDRESS_PROG:'UPDATE_ADDRESS_PROG',
    UPDATE_ADDRESS_SUCC:'UPDATE_ADDRESS_SUCC',
    UPDATE_ADDRESS_FAIL:'UPDATE_ADDRESS_FAIL',

};