export const AuthActionTypes = {
    LOGIN_PROG: 'LOGIN_PROG',
    LOGIN_SUCC: 'LOGIN_SUCC',
    LOGIN_FAIL: 'LOGIN_FAIL',

    SET_USER: 'SET_USER',

    LOGOUT: 'LOGOUT',

    CLEAR_ERROR: 'CLEAR_ERROR',

    GET_NEW_ACCESS_TOKEN_PROG: 'GET_NEW_ACCESS_TOKEN_PROG',
    GET_NEW_ACCESS_TOKEN_SUCC: 'GET_NEW_ACCESS_TOKEN_SUCC',
    GET_NEW_ACCESS_TOKEN_FAIL: 'GET_NEW_ACCESS_TOKEN_FAIL',

    SOCIAL_LOGIN_PROG: 'SOCIAL_LOGIN_PROG',
    SOCIAL_LOGIN_SUCC: 'SOCIAL_LOGIN_SUCC',
    SOCIAL_LOGIN_FAIL: 'SOCIAL_LOGIN_FAIL',

    GET_PROFILE_PROG: 'GET_PROFILE_PROG',
    GET_PROFILE_SUCC: 'GET_PROFILE_SUCC',
    GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',

    UPDATE_PROFILE_PROG: 'UPDATE_PROFILE_PROG',
    UPDATE_PROFILE_SUCC: 'UPDATE_PROFILE_SUCC',
    UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',
    CLEAR_SUCCESS: 'CLEAR_SUCCESS'

};