export const CardActionTypes = {
    GET_CARDS_PROG: 'GET_CARDS_PROG',
    GET_CARDS_SUCC: 'GET_CARDS_SUCC',
    GET_CARDS_FAIL: 'GET_CARDS_FAIL',

    SAVE_CARD_PROG:'SAVE_CARD_PROG',
    SAVE_CARD_SUCC:'SAVE_CARD_SUCC',
    SAVE_CARD_FAIL:'SAVE_CARD_FAIL',

    DELETE_CARD_PROG:'DELETE_CARD_PROG',
    DELETE_CARD_SUCC:'DELETE_CARD_SUCC',
    DELETE_CARD_FAIL:'DELETE_CARD_FAIL',

};