export const OrderActionTypes = {
    GET_ORDERS_PROG: 'GET_ORDERS_PROG',
    GET_ORDERS_SUCC: 'GET_ORDERS_SUCC',
    GET_ORDERS_FAIL: 'GET_ORDERS_FAIL',

    GET_ORDER_DETAIL_PROG: 'GET_ORDER_DETAIL_PROG',
    GET_ORDER_DETAIL_SUCC: 'GET_ORDER_DETAIL_SUCC',
    GET_ORDER_DETAIL_FAIL: 'GET_ORDER_DETAIL_FAIL',

    CLEAR_ORDER_DETAIL: 'CLEAR_ORDER_DETAIL',

    GET_ACTIVE_ORDERS_PROG: 'GET_ACTIVE_ORDERS_PROG',
    GET_ACTIVE_ORDERS_SUCC: 'GET_ACTIVE_ORDERS_SUCC',
    GET_ACTIVE_ORDERS_FAIL: 'GET_ACTIVE_ORDERS_FAIL',

    POST_ORDER_PROG: 'POST_ORDER_PROG',
    POST_ORDER_SUCC: 'POST_ORDER_SUCC',
    POST_ORDER_FAIL: 'POST_ORDER_FAIL',

    MAKE_PAYMENT_PROG: 'MAKE_PAYMENT_PROG',
    MAKE_PAYMENT_SUCC: 'MAKE_PAYMENT_SUCC',
    MAKE_PAYMENT_FAIL: 'MAKE_PAYMENT_FAIL',

    UPDATE_ORDER_PROG: 'UPDATE_ORDER_PROG',
    UPDATE_ORDER_SUCC: 'UPDATE_ORDER_SUCC',
    UPDATE_ORDER_FAIL: 'UPDATE_ORDER_FAIL',

    CANCEL_ORDER_PROG: 'CANCEL_ORDER_PROG',
    CANCEL_ORDER_SUCC: 'CANCEL_ORDER_SUCC',
    CANCEL_ORDER_FAIL: 'CANCEL_ORDER_FAIL',

    SET_PICKUP_AND_DROPOFF: 'SET_PICKUP_AND_DROPOFF',


    ORDER_START: 'ORDER_START',

    CLEAR_ORDER: 'CLEAR_ORDER',

    SET_ORDER: 'SET_ORDER',
    SET_CURRENT_ORDER: 'SET_CURRENT_ORDER',
};