export const OrderActionTypes = {
    GET_ORDERS_PROG: 'GET_ORDERS_PROG',
    GET_ORDERS_SUCC: 'GET_ORDERS_SUCC',
    GET_ORDERS_FAIL: 'GET_ORDERS_FAIL',

    POST_ORDER_PROG: 'POST_ORDER_PROG',
    POST_ORDER_SUCC: 'POST_ORDER_SUCC',
    POST_ORDER_FAIL: 'POST_ORDER_FAIL',

    // UPDATE_ORDER_PROG: 'UPDATE_ORDER_PROG',
    // UPDATE_ORDER_SUCC: 'UPDATE_ORDER_SUCC',
    // UPDATE_ORDER_FAIL: 'UPDATE_ORDER_FAIL',

    CANCEL_ORDER_PROG: 'CANCEL_ORDER_PROG',
    CANCEL_ORDER_SUCC: 'CANCEL_ORDER_SUCC',
    CANCEL_ORDER_FAIL: 'CANCEL_ORDER_FAIL',

    SET_PICKUP_AND_DROPOFF: 'SET_PICKUP_AND_DROPOFF',
    ORDER_START: 'ORDER_START'
};